### ISSUE TITLE
Javascript script tags

### ISSUE THREAD

**Issue by kingsleyh** [clearsightstudio/apex#8]
I want to put a javascript script tag in the body of my document to load a tumult hype app. But the mime type is not recognised:

     
     <div id="sotapp2_hype_container" style="margin:auto;position:relative;width:375px;height:559px;overflow:hidden;" aria-live="polite">
         <script type="text/javascript" charset="utf-8" src="http://localhost:8080/sotapp2.hyperesources/sotapp2_hype_generated_script.js?55146"></script>
    </div>

I get an error in the javascript console:

    Resource interpreted as Script but transferred with MIME type text/html: "http://localhost:8080/sotapp2.hyperesources/sotapp2_hype_generated_script.js?55146".

I assume this is because the only response_type values supported are :json or :html and it doesn't know how to handle javascript. 

I don't know how to fix this but assume I need to add another handler here:

    case response_type
              when :html
                GCDWebServerDataResponse.responseWithHTML(apply_layout(response, layout))
              when :json
                GCDWebServerDataResponse.responseWithJSONObject(apply_layout(response, layout))
              # TODO, do the the rest of the types
              end

Would this be a simple fix? I really want to use Apex to serve my hype 3 application

**Comment by jamonholmgren** [comment]
Hey @kingsleyh ! I think you're right (it's been a while since I last worked on this). If you want to dig into it and submit a PR, that would be fantastic.

**Comment by kingsleyh** [comment]
I think that I could use the general GCDWebServerDataResponse.responseWithData which creates a response with a given content type

https://github.com/swisspol/GCDWebServer/blob/master/GCDWebServer/Responses/GCDWebServerDataResponse.h

I've forked Apex and will give it a go

**Comment by kingsleyh** [comment]
I got it working - but it doesn't seem like I should have to do what I did. I'm not really sure the best way to fix it - but I guess this is a temporary hack - I don't feel like it's good enough for other people to use. I check if the filename ends with .js and the read the file and return the content with the text/javascript mime type:

     elsif request.raw.path.include?('.js')
             jsfile = NSBundle.mainBundle.pathForResource("assets", ofType:nil) + request.raw.path
             response = File.read(jsfile)       
              GCDWebServerDataResponse.responseWithData(response.to_data, contentType:"text/javascript") 
            else
              response = "<h1>404 not found</h1>"
              GCDWebServerDataResponse.responseWithHTML(apply_layout(response, layout))
            end

**Comment by kingsleyh** [comment]
thats in server.rb

**Comment by jamonholmgren** [comment]
@twerth, you've used this gem. Does it seem reasonable to do the above, or is there a better approach?

**Comment by kingsleyh** [comment]
I feel that there should be someway for the static file server to just server whatever is in the assets folder and not have to worry about the mime type. Or set the available mime types at that point rather than having to read the file content and then serve it up.

**Comment by twerth** [comment]
I think that's a fine way. You have to read the file anyways and serve it correct? 

If you wanted to serve content as javascript that didn't end with .js, you'd have to setup a routing system.

**Comment by kingsleyh** [comment]
I'll add some error handling in case the file is not found on the file system and send a pull request. This is quite cool as I can now serve my tumult hype application from an iOS app with only a few lines of code
